### ISSUE TITLE
Runtime error while running demo

### ISSUE THREAD

**Issue by bustardeuhedral** [qfgaohao/pytorch-ssd#10]
Hi,
when I'm trying to run Open Images Dataset demo (with handguns), I get the following error:
`Traceback (most recent call last):
File "run_ssd_example.py", line 22, in <module>
    net.load(model_path)
File "/home/bustardeuhedral/pytorch-ssd/vision/ssd/ssd.py", line 119, in load
    self.load_state_dict(torch.load(model, map_location=lambda storage, loc: storage))
File "/home/bustardeuhedral/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719
, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SSD:
        Missing key(s) in state_dict: "base_net.0.weight", "base_net.0.bias", "base_net.2.weight", "base_net.2.bias
", "base_net.5.weight", "base_net.5.bias", "base_net.7.weight", "base_net.7.bias", "base_net.10.weight", "base_net.
10.bias", "base_net.12.weight", "base_net.12.bias", "base_net.14.weight", "base_net.14.bias", "base_net.17.weight",
 "base_net.17.bias", "base_net.19.weight", "base_net.19.bias", "base_net.21.weight", "base_net.21.bias", "base_net.
24.weight", "base_net.24.bias", "base_net.26.weight", "base_net.26.bias", "base_net.28.weight", "base_net.28.bias",
 "base_net.31.weight", "base_net.31.bias", "base_net.33.weight", "base_net.33.bias", "source_layer_add_ons.0.weight
", "source_layer_add_ons.0.bias", "source_layer_add_ons.0.running_mean", "source_layer_add_ons.0.running_var". 
        Unexpected key(s) in state_dict: "base_net.0.0.weight", "base_net.0.1.weight", "base_net.0.1.bias", "base_n
et.0.1.running_mean", "base_net.0.1.running_var", "base_net.1.0.weight", "base_net.1.1.weight", "base_net.1.1.bias"
, "base_net.1.1.running_mean", "base_net.1.1.running_var", "base_net.1.3.weight", "base_net.1.4.weight", "base_net.
1.4.bias", "base_net.1.4.running_mean", "base_net.1.4.running_var", "base_net.2.0.weight", "base_net.2.1.weight", "
base_net.2.1.bias", "base_net.2.1.running_mean", "base_net.2.1.running_var", "base_net.2.3.weight", "base_net.2.4.w
eight", "base_net.2.4.bias", "base_net.2.4.running_mean", "base_net.2.4.running_var", "base_net.3.0.weight", "base_
net.3.1.weight", "base_net.3.1.bias", "base_net.3.1.running_mean", "base_net.3.1.running_var", "base_net.3.3.weight
", "base_net.3.4.weight", "base_net.3.4.bias", "base_net.3.4.running_mean", "base_net.3.4.running_var", "base_net.4
.0.weight", "base_net.4.1.weight", "base_net.4.1.bias", "base_net.4.1.running_mean", "base_net.4.1.running_var", "b
ase_net.4.3.weight", "base_net.4.4.weight", "base_net.4.4.bias", "base_net.4.4.running_mean", "base_net.4.4.running
_var", "base_net.5.0.weight", "base_net.5.1.weight", "base_net.5.1.bias", "base_net.5.1.running_mean", "base_net.5.
1.running_var", "base_net.5.3.weight", "base_net.5.4.weight", "base_net.5.4.bias", "base_net.5.4.running_mean", "ba
se_net.5.4.running_var", "base_net.6.0.weight", "base_net.6.1.weight", "base_net.6.1.bias", "base_net.6.1.running_m
ean", "base_net.6.1.running_var", "base_net.6.3.weight", "base_net.6.4.weight", "base_net.6.4.bias", "base_net.6.4.
running_mean", "base_net.6.4.running_var", "base_net.7.0.weight", "base_net.7.1.weight", "base_net.7.1.bias", "base
_net.7.1.running_mean", "base_net.7.1.running_var", "base_net.7.3.weight", "base_net.7.4.weight", "base_net.7.4.bia
s", "base_net.7.4.running_mean", "base_net.7.4.running_var", "base_net.8.0.weight", "base_net.8.1.weight", "base_ne
t.8.1.bias", "base_net.8.1.running_mean", "base_net.8.1.running_var", "base_net.8.3.weight", "base_net.8.4.weight",
 "base_net.8.4.bias", "base_net.8.4.running_mean", "base_net.8.4.running_var", "base_net.9.0.weight", "base_net.9.1
.weight", "base_net.9.1.bias", "base_net.9.1.running_mean", "base_net.9.1.running_var", "base_net.9.3.weight", "bas
e_net.9.4.weight", "base_net.9.4.bias", "base_net.9.4.running_mean", "base_net.9.4.running_var", "base_net.10.0.wei
ght", "base_net.10.1.weight", "base_net.10.1.bias", "base_net.10.1.running_mean", "base_net.10.1.running_var", "bas
e_net.10.3.weight", "base_net.10.4.weight", "base_net.10.4.bias", "base_net.10.4.running_mean", "base_net.10.4.runn
ing_var", "base_net.11.0.weight", "base_net.11.1.weight", "base_net.11.1.bias", "base_net.11.1.running_mean", "base
_net.11.1.running_var", "base_net.11.3.weight", "base_net.11.4.weight", "base_net.11.4.bias", "base_net.11.4.running_mean", "base_net.11.4.running_var", "base_net.12.0.weight", "base_net.12.1.weight", "base_net.12.1.bias", "base_net.12.1.running_mean", "base_net.12.1.running_var", "base_net.12.3.weight", "base_net.12.4.weight", "base_net.12.4.bias", "base_net.12.4.running_mean", "base_net.12.4.running_var", "base_net.13.0.weight", "base_net.13.1.weight", "base_net.13.1.bias", "base_net.13.1.running_mean", "base_net.13.1.running_var", "base_net.13.3.weight", "base_net.13.4.weight", "base_net.13.4.bias", "base_net.13.4.running_mean", "base_net.13.4.running_var". 
        size mismatch for classification_headers.0.weight: copying a param of torch.Size([12, 512, 3, 3]) from checkpoint, where the shape is torch.Size([18, 512, 3, 3]) in current model.
        size mismatch for classification_headers.0.bias: copying a param of torch.Size([12]) from checkpoint, where the shape is torch.Size([18]) in current model.
        size mismatch for classification_headers.4.weight: copying a param of torch.Size([12, 256, 3, 3]) from checkpoint, where the shape is torch.Size([18, 256, 3, 3]) in current model.
        size mismatch for classification_headers.4.bias: copying a param of torch.Size([12]) from checkpoint, where the shape is torch.Size([18]) in current model.
        size mismatch for classification_headers.5.weight: copying a param of torch.Size([12, 256, 3, 3]) from checkpoint, where the shape is torch.Size([18, 256, 3, 3]) in current model.
        size mismatch for classification_headers.5.bias: copying a param of torch.Size([12]) from checkpoint, where the shape is torch.Size([18]) in current model.
        size mismatch for regression_headers.0.weight: copying a param of torch.Size([16, 512, 3, 3]) from checkpoint, where the shape is torch.Size([24, 512, 3, 3]) in current model.
        size mismatch for regression_headers.0.bias: copying a param of torch.Size([16]) from checkpoint, where the shape is torch.Size([24]) in current model.
        size mismatch for regression_headers.4.weight: copying a param of torch.Size([16, 256, 3, 3]) from checkpoint, where the shape is torch.Size([24, 256, 3, 3]) in current model.
        size mismatch for regression_headers.4.bias: copying a param of torch.Size([16]) from checkpoint, where the shape is torch.Size([24]) in current model.
        size mismatch for regression_headers.5.weight: copying a param of torch.Size([16, 256, 3, 3]) from checkpoint, where the shape is torch.Size([24, 256, 3, 3]) in current model.
        size mismatch for regression_headers.5.bias: copying a param of torch.Size([16]) from checkpoint, where the shape is torch.Size([24]) in current model.`
The same error after training on Open Images Dataset (from scratch and using pretrained `mobilenet-v1-ssd-mp-0_675.pth`).
I am using python3.6.7 with pytorch 0.4.1

**Comment by qfgaohao** [comment]
Hi @bustardeuhedral It's a bug. I forgot to change this file when I changed the related parts.  I will fix it and let you know.

**Comment by qfgaohao** [comment]
@bustardeuhedral fixed. Plz see the commit. https://github.com/qfgaohao/pytorch-ssd/commit/57de5e4edf94382e6bef368bf0e812baa550e2f6

**Comment by bustardeuhedral** [comment]
@qfgaohao Thanks, now it works
