### ISSUE TITLE
About coordconv ideas

### ISSUE THREAD

**Issue by AIprogrammer** [qfgaohao/pytorch-ssd#108]
Does the repo include the coord conv ideas? I didn't find the implementation in this repo. Does anyone know where should we add the coord conv layers?

**Comment by qfgaohao** [comment]
@AIprogrammer It's in a branch. https://github.com/qfgaohao/pytorch-ssd/blob/coordconv/vision/nn/coord.py  . You can simply insert this layer as the first layer of your model.

**Comment by AIprogrammer** [comment]
Thanks for your reply. I will have a try.
