### ISSUE TITLE
Multi GPU training

### ISSUE THREAD

**Issue by sophia-wright-blue** [qfgaohao/pytorch-ssd#16]
when training a model using ```train_ssd.py```, what changes would we need to make to use multiple GPUs for training?  thanks,

**Comment by qfgaohao** [comment]
I haven't tried. I am not sure if using "torch.nn.parallel.data_parallel" will be enough. If you can make it work, please feel free to create a pull request. Thanks!

**Comment by sophia-wright-blue** [comment]
thanks for replying @qfgaohao , will give it a shot

**Comment by niranjanravilevelup** [comment]
Hi,
   Were you successful in multi-GPU part?
