### ISSUE TITLE
download openimages 

### ISSUE THREAD

**Issue by TengFei75882341** [qfgaohao/pytorch-ssd#17]
Hi! First of all thank you for this working implementation of SSD in pytorch.

I want to retrain ssd with open image ,so I tried to use open_images_downloader.py to download the datasets.Like this.
python3 open_images_downloader.py --root ./data/open_images --class_names "Handgun,Shotgun" --num_workers 10
I can get all the csv file, but can't get the image "Handgun,Shotgun"
so I debug the code
and the code stop at here

s3.download_file(bucket, src, dest)

and the arg src input like this 'train/0000271195f2c007.jpg'
the arg dest input like this './data/open_images/train/0000271195f2c007.jpg'
but still cannot download image
Thanks in advance!

**Comment by qfgaohao** [comment]
@TengFei75882341 any exceptions you can see when you run the program?

**Comment by TengFei75882341** [comment]
@qfgaohao just stop at there ,Now I use the script that can download the image,thanks for your  sharing again.
