### ISSUE TITLE
Run ssd_sample.py with mb2-ssd-lite ERROR 

### ISSUE THREAD

**Issue by ZLeopard** [qfgaohao/pytorch-ssd#20]
there‘s a little bug in the code. when i run the file to test a image with the mobilenetv2-ssdlite, got a TensorType ERROR, So i change the default params of "create_mobilenetv2_ssd_lite_predictor" in the file **mobilenet_v2_ssd_lite.py** . by set the device as **None**

> def create_mobilenetv2_ssd_lite_predictor(net, candidate_size=200, nms_method=None, sigma=0.5, device=None):

Any better suggestion? i learn a lot from your code, thank you a lot. 太感谢啦~~

**Comment by ZLeopard** [comment]
I will try to train the shufflenetv2 using this code, if got some result, I will tell you~~your code is amazing, thanks again!

**Comment by qfgaohao** [comment]
@ZLeopard That's good. None is better. Looking forward to your shufflenetv2 implementation. Happy coding!

**Comment by hahanigehaha233** [comment]
You should make a MR.
