### ISSUE TITLE
How to modify the image_size in the ssd/config directory

### ISSUE THREAD

**Issue by wangnamu** [qfgaohao/pytorch-ssd#22]
Hello @qfgaohao , I want to reduce the image_size in the mobilenetv1_ssd_config.py file, such as from 300 to 100, if you adjust this, you do not need to modify specs = [
     SSDSpec(19, 16, SSDBoxSizes(60, 105), [2, 3]),
     SSDSpec(10, 32, SSDBoxSizes(105, 150), [2, 3]),
     SSDSpec(5, 64, SSDBoxSizes(150, 195), [2, 3]),
     SSDSpec(3, 100, SSDBoxSizes(195, 240), [2, 3]),
     SSDSpec(2, 150, SSDBoxSizes(240, 285), [2, 3]),
     SSDSpec(1, 300, SSDBoxSizes(285, 330), [2, 3])
],Thank you

**Comment by wangnamu** [comment]
:)

**Comment by qfgaohao** [comment]
Hi @wangnamu , you can modify mobilenetv1_ssd_config.py and mobilenetv1_ssd.py to use a new size.  It's not very straightforward at the moment, as you have to coordinate the generated anchors/priors and  the classification head. Understanding the process of anchor/prior generation can also help.  Btw, if you aim to increase the speed, using a lighter base net might be easier and better than using smaller input. For example, using a mobile net with width_multi 0.5 will significantly increase the speed.

**Comment by wangnamu** [comment]
I will try a lighter base network, thank you very much.

**Comment by juanmanpr** [comment]
@qfgaohao Hello there!
I am actually interested in trying input images of size 512x512. Can you please point me out in the rigth direction to achieve this?

Thanks a lot!

**Comment by HongChow** [comment]
> Hi @wangnamu , you can modify mobilenetv1_ssd_config.py and mobilenetv1_ssd.py to use a new size. It's not very straightforward at the moment, as you have to coordinate the generated anchors/priors and the classification head. Understanding the process of anchor/prior generation can also help. Btw, if you aim to increase the speed, using a lighter base net might be easier and better than using smaller input. For example, using a mobile net with width_multi 0.5 will significantly increase the speed.
@qfgaohao hi, may I ask a stupid question: could we using the pretrained model if we using a total different image_size such as 900*900?

**Comment by HongChow** [comment]
> Hi @wangnamu , you can modify mobilenetv1_ssd_config.py and mobilenetv1_ssd.py to use a new size. It's not very straightforward at the moment, as you have to coordinate the generated anchors/priors and the classification head. Understanding the process of anchor/prior generation can also help. Btw, if you aim to increase the speed, using a lighter base net might be easier and better than using smaller input. For example, using a mobile net with width_multi 0.5 will significantly increase the speed.

@qfgaohao hi, may I ask a stupid question: could we using the pretrained model if we using a total different image_size such as 900*900?

**Comment by qfgaohao** [comment]
@HongChow It may still help, even not as much as using pretrained models with similar data. As far as I know, transfer learning in computer vision is not working as well as in Natural Language Processing. Pretrained models mainly help weight intialization rather than final representation learning.

**Comment by bjbraun** [comment]
@qfgaohao Thanks a lot for your great work!
I am currently also trying a different image size and I am actually just stuck at one point. 
If I use an image of in my case 848x480, I get a tensor of 12870 for the confidences.

So I need to adjust the priors such that I get the same size right? I would need to adjust the numbers in the SSDSpec, e.g. the 19,10... such that 19*19*6+.... is equal to 12870.

My question is, can I choose the numbers 19,10, etc. randomly or do they have to follow a certain pattern? Or could I just use for example 38,19,....

Thank you really much for your help!

**Comment by phamkhactu** [comment]
Hi @qfgaohao I want to change config for car detection, I know that the config has used for 21 classifications, but i train the model  again with car UA-Detrac. The model shows bad. such as: one car have 2 or 3 anchors predictions, not well to catch car. Thanks in adavance.
