### ISSUE TITLE
Does it support converting  SSDLITE_MOBILENETV2 of  pytorch format to caffe2 formate?

### ISSUE THREAD

**Issue by peterpaniff** [qfgaohao/pytorch-ssd#34]

**Comment by qfgaohao** [comment]
As said in the README, "The above MobileNetV2 SSD-Lite model is not ONNX-Compatible, as it uses Relu6 which is not supported by ONNX. The code supports the ONNX-Compatible version. Once I have trained a good enough MobileNetV2 model with Relu, I will upload the corresponding Pytorch and Caffe2 models."  

In other words, you have train a MobileNetV2 model with Relu first.

**Comment by peterpaniff** [comment]
thank you
