### ISSUE TITLE
"AttributeError: 'collections.OrderedDict' object has no attribute 'state_dict"

### ISSUE THREAD

**Issue by HongChow** [qfgaohao/pytorch-ssd#36]
hi
I am using mmdnn to convert your net to other platform.

I can successfully run the restnet18 and restnet34 downloaded by “mmdownload”
but error occurs converting my own model:
File “/usr/local/lib/python3.5/dist-packages/torch/jit/init.py”, line 259, in _unique_state_dict
state_dict = module.state_dict(keep_vars=keep_vars)
AttributeError: ‘collections.OrderedDict’ object has no attribute ‘state_dict’

So maybe the environment is OK,There must be something wrong with my pth ,In my python code :
net.load(model_path)
torch.save(net.state_dict(),‘mb_v1_ssd.pth’)

here, model_path is a pth path(pth file) pretrained by others

Both the model_path’s pth and the mb_v1_ssd.pth output the same error
“AttributeError: ‘collections.OrderedDict’ object has no attribute 'state_dict”

because mmdnn asks a full model saved.
then I did this :
torch.save(net,'mb_v1_ssd_all.pth')
this operation make an error in your code:
 File "/home/hong/anaconda3/envs/PyTorch1.0_GPU_ONNX/lib/python3.7/site-packages/torch/serialization.py", line 291, in _save
    pickler.dump(obj)
TypeError: can't pickle module objects

Could someone help?

**Comment by qfgaohao** [comment]
"torch.save(net,'mb_v1_ssd_all.pth')" should be "torch.save(net.state_dict(),'mb_v1_ssd_all.pth')". Otherwise, I couldn't see where the problem is either.

**Comment by HongChow** [comment]
> "torch.save(net,'mb_v1_ssd_all.pth')" should be "torch.save(net.state_dict(),'mb_v1_ssd_all.pth')". Otherwise, I couldn't see where the problem is either.

**Comment by HongChow** [comment]
hi,  thank you for reply,
I've tried "torch.save(net.state_dict(),'mb_v1_ssd_all.pth')" , it do can save pth file ,but when i use mmdnn to convert the torch net（using the saved pth）, an error occurs: "AttributeError: 'collections.OrderedDict' object has no attribute 'state_dict'" . 
The is reason is the whole net (including both architecture and weights) is needed using mmdnn. 
please kindly refer to the FAQ of mmdnn's pytorch instruction :
https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/README.md#faq
So the point maybe is : how to save the whole net ?
 would you please give me some idea?
