### ISSUE TITLE
PRETRAINED MODEL LINK NOT VALID

### ISSUE THREAD

**Issue by ram1897** [qfgaohao/pytorch-ssd#4]
Hi,
I am not able to open the link as such or even using wget.
When using wget this t=is the error I am getting:

**"2018-08-25 19:34:19 ERROR 403: Forbidden."**

**Comment by qfgaohao** [comment]
@ram1897 sorry, it's my bad.  I forgot to deal with my google cloud bills. It's ok now. Thanks for letting me know.
