### ISSUE TITLE
Ground Truth bounding boxes have negative values and values more 1

### ISSUE THREAD

**Issue by pratikm141** [qfgaohao/pytorch-ssd#41]
The ground truth bounding boxes given by the train loader have negative values and even values > 1 (meaning bounding box has more width/height than the actual image).. whereas in the Annotations for VOC all the values are within the file size. 

Is this a normal transformation. If so then how to obtain the actual bounding box location in the image?

**Comment by mike9251** [comment]
I also get negative and > 1 values for box coordinates during inference. Maybe during training such values also occur (I haven't checked that).

@pratikm141 Have you figured out how to interpret those values?

**Comment by mike9251** [comment]
My bad, I added custom data loader and made a mistake - box coordinates were calculated in relative values. Now everything works, thanks!
