### ISSUE TITLE
How to convert the model to a "Caffe" model

### ISSUE THREAD

**Issue by frizk123** [qfgaohao/pytorch-ssd#42]

**Comment by qfgaohao** [comment]
plz check this file https://github.com/qfgaohao/pytorch-ssd/blob/master/convert_to_caffe2_models.py

**Comment by frizk123** [comment]
@qfgaohao  Thank you for your replay. However, I want to convert the model to "caffe" format, not "caffe2" format. I am not very clear about the difference between "caffe" and "caffe2"

**Comment by qfgaohao** [comment]
@frizk123 very different. they are not compatible at all. If you check out the above script, you will see the pytorch model is converted to ONNX, and then converted to Caffe2. You may replace the 'ONNX->Caffe2' step with 'ONNX->Caffe' to get a Caffe model.
