### ISSUE TITLE
val_dataset in train_ssd.py

### ISSUE THREAD

**Issue by scarmaten** [qfgaohao/pytorch-ssd#45]
Hey in train_ssd.py,

val_dataset = OpenImagesDataset(dataset_path,
                                        transform=test_transform, target_transform=target_transform,
                                        dataset_type="test")

shouldn't it be this instead?

val_dataset = OpenImagesDataset(dataset_path,
                                        transform=test_transform, target_transform=target_transform,
                                        dataset_type="validation")

**Comment by qfgaohao** [comment]
Hey, it's not uncommon to treat 'validation' as a kind of 'test'.
