### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by liuyizhuang** [qfgaohao/pytorch-ssd#62]

**Comment by zgq91** [comment]
How do you solve this problem?

**Comment by liuyizhuang** [comment]
could you tell me the error .i have forgeted it.sorry

**Comment by liuyizhuang** [comment]
> How do you solve this problem?

could you tell me the error code.i have forgot it.sorry

**Comment by conan13101998** [comment]
I got this message when run train_ssd.py with voc type data set 
![image](https://user-images.githubusercontent.com/28443198/69904091-fa351a00-13d4-11ea-8a8a-c8da13f528d4.png)

**Comment by arthursdays** [comment]
Same

**Comment by neeveermoree** [comment]
@liuyizhuang @zgq91 @conan13101998 @arthursdays
I am having the exact same problem. Have you solved it?

**Comment by MaddyThakker** [comment]
@neeveermoree did you solve it?

**Comment by MaddyThakker** [comment]
@neeveermoree change classes labels.

**Comment by ChetanPatil28** [comment]
If **box_a** or **box_b**  don't contain any object , then this error occurs.
Basically, this issue occurs in the fucntion **__get__item()** from **voc_dataset.py** 
Before the **image = self._read_image(image_id)** line, try to print what is the shape of **boxes**.
Possibility is that its an empty array.!
