### ISSUE TITLE
Training without pretrain model

### ISSUE THREAD

**Issue by zhanglaplace** [qfgaohao/pytorch-ssd#63]
thanks for your great jobs!
could you show me the training log without pretrain model ?  
i modify the network backbone and training network using init param not pretrain model.
i using the default param . whether i should change training param like init_lr ,batch_size .
![image](https://user-images.githubusercontent.com/12178974/61989371-dd708a80-b060-11e9-97dd-e6a45c83b8ea.png)

**Comment by qfgaohao** [comment]
Hi @zhanglaplace . I don't have one for public datasets. Maybe you can reference the params for COCO dataset, which doesn't require pre-trained models.

**Comment by zhanglaplace** [comment]
@qfgaohao 嗯，我这边简单修改了下模型结构，map也还可以，非常👍的repo
