### ISSUE TITLE
ncnn output scores result mismatch pytorch result

### ISSUE THREAD

**Issue by zhanglaplace** [qfgaohao/pytorch-ssd#68]
你好，我这边把mb1-ssd的模型，转化为onnx,再通过onnx转化为ncnn的模型，在forword的时候，打印出scores的输出是3000\*21，boxes的输出是12000(3000\*4。同一张图对比了进行forword前的送入数据是完全一样的。但是输出的第一个框的box的scores差异比较大，ncnn的值每个类别平均，而pytorch的为背景。
![image](https://user-images.githubusercontent.com/12178974/63482240-c2abfd00-c4ca-11e9-8f83-1ea2b4b0b80c.png)

-    pytorch
![image](https://user-images.githubusercontent.com/12178974/63482265-d7889080-c4ca-11e9-9fbc-1bfbc3568b69.png)

-    ncnn
![image](https://user-images.githubusercontent.com/12178974/63482278-e8390680-c4ca-11e9-83c1-e6acd4cd5af2.png)

**Comment by zhanglaplace** [comment]
看了下param的设置，应该是还有部分的输入值没有指定。其中的MemoryData的意义应该和anchros的设定有关把
![image](https://user-images.githubusercontent.com/12178974/63483094-db69e200-c4cd-11e9-8c00-a458f4957928.png)

**Comment by qfgaohao** [comment]
不了解NCNN，不过看起来越来越流行了。:-D

**Comment by zhanglaplace** [comment]
@qfgaohao 移动端的部署非常方便，

**Comment by zhanglaplace** [comment]
@qfgaohao 这边转化并测试了下，ncnn是可以跑通的 😄

**Comment by zhoujinhai** [comment]
@zhanglaplace 你好，请问转换之后ncnn运行有结果吗，我这边pytorch训练的模型是mobilenetv2-ssd，跑完在pytorch下测试是可以检测的，但pth->onnx->simple onnx->ncnn转换后再ncnn下检测不到。
