### ISSUE TITLE
RuntimeError when running live demo on pytorch

### ISSUE THREAD

**Issue by seongkyun** [qfgaohao/pytorch-ssd#8]
I've installed Pytorch 0.4.1 CUDA version and ran this code
(CUDA 9.0 with cuDNN v7.1, GTX Titan X)

`python3 run_ssd_live_demo.py mb1-ssd models/mobilenet-v1-ssd-mp-0_675.pth models/voc-model-labels.txt `

and it prints out 

>Traceback (most recent call last):
>  File "run_ssd_live_demo.py", line 62, in <module>
>    boxes, labels, probs = predictor.predict(image, 10, 0.4)
>  File "/home/han/study/pytorch-ssd/vision/ssd/predictor.py", line 37, in predict
>    scores, boxes = self.net.forward(images)
>  File "/home/han/study/pytorch-ssd/vision/ssd/ssd.py", line 77, in forward
>    locations, self.priors, self.config.center_variance, self.config.size_variance
>  File "/home/han/study/pytorch-ssd/vision/utils/box_utils.py", line 104, in convert_locations_to_boxes
>    locations[..., :2] * center_variance * priors[..., 2:] + priors[..., :2],
>RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'other'

I think the problem is network on CPU, not on GPU. So tired to make network on GPU to use
`net = net.cuda()` but same error is occured.

My only difference is Python 3.5 and uses `ww` pip binary to avoid F-string syntax error on Python 3.5.

Help me guyz.

**Comment by faresbs** [comment]
I had the same problem before. the problem here is that the variable 'priors' needs to be a torch tensor not a cuda tensor. so you can simply transform priors from gpu to cpu by using this : 
priors = priors.cpu()
before the "locations[..., :2] * center_variance * priors[..., 2:] + priors[..., :2]"

**Comment by qfgaohao** [comment]
@seongkyun you can also set the device of the predictor as folllows in the run_ssd_live_demo.py file.
```
DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
predictor = create_mobilenetv1_ssd_predictor(net, device=DEVICE)
```

Anyway, it's a bug. I've fixed it  by changing the default device from cpu to GPU if GPU is available

**Comment by seongkyun** [comment]
Solved. Thanks, @faresbs  and @qfgaohao .
