### ISSUE TITLE
Bug: mobilenetv2_ssd_lite_predictor

### ISSUE THREAD

**Issue by bjbraun** [qfgaohao/pytorch-ssd#85]
Hey,

I think in the file "mobilenet_v2_ssd_lite.py" is a small bug. The function below is defined as:

def create_mobilenetv2_ssd_lite_predictor(net, candidate_size=200, nms_method=None, sigma=0.5, device=torch.device('cpu'):

However, when you try to run "run_ssd_example.py" and a GPU is available, you get the error "RuntimeError: expected device cpu and dtype Float but got device cuda:0 and dtype Float"

I changed the function to:

def create_mobilenetv2_ssd_lite_predictor(net, candidate_size=200, nms_method=None, sigma=0.5, device=torch.device("cuda:0" if torch.cuda.is_available() else "cpu")):

Now everything is working fine.

**Comment by vladserkoff** [comment]
Since it's a default value of the parameter you should just pass the proper device instance when calling this function and not rely on the default value.

**Comment by bjbraun** [comment]
Ah alright, thank you!
