### ISSUE TITLE
size mismatch for classification_headers.5.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([12]) in current model.

### ISSUE THREAD

**Issue by mekong0404** [qfgaohao/pytorch-ssd#93]
Hi
When i try to run demo script "run_ssd_live_demo.py" for trained model of 1 class i get this error. size mismatch.
Traceback (most recent call last):
  File "run_ssd_live_demo.py", line 41, in <module>
    net.load(model_path)
  File "/Users/mekong/git/pytorch-ssd/vision/ssd/ssd.py", line 135, in load
    self.load_state_dict(torch.load(model, map_location=lambda storage, loc: storage))
  File "/Users/mekong/git/pytorch-ssd/ssd-pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SSD:
	size mismatch for classification_headers.0.weight: copying a param of torch.Size([126, 512, 3, 3]) from checkpoint, where the shape is torch.Size([12, 512, 3, 3]) in current model.
	size mismatch for classification_headers.0.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([12]) in current model.
	size mismatch for classification_headers.1.weight: copying a param of torch.Size([126, 1024, 3, 3]) from checkpoint, where the shape is torch.Size([12, 1024, 3, 3]) in current model.
	size mismatch for classification_headers.1.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([12]) in current model.
	size mismatch for classification_headers.2.weight: copying a param of torch.Size([126, 512, 3, 3]) from checkpoint, where the shape is torch.Size([12, 512, 3, 3]) in current model.
	size mismatch for classification_headers.2.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([12]) in current model.
	size mismatch for classification_headers.3.weight: copying a param of torch.Size([126, 256, 3, 3]) from checkpoint, where the shape is torch.Size([12, 256, 3, 3]) in current model.
	size mismatch for classification_headers.3.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([12]) in current model.
	size mismatch for classification_headers.4.weight: copying a param of torch.Size([126, 256, 3, 3]) from checkpoint, where the shape is torch.Size([12, 256, 3, 3]) in current model.
	size mismatch for classification_headers.4.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([12]) in current model.
	size mismatch for classification_headers.5.weight: copying a param of torch.Size([126, 256, 3, 3]) from checkpoint, where the shape is torch.Size([12, 256, 3, 3]) in current model.
	size mismatch for classification_headers.5.bias: copying a param of torch.Size([126]) from checkpoint, where the shape is torch.Size([12]) in current model.

i have tried torch=1.0.0, torch=0.4.1

please help me

**Comment by dariocazzani** [comment]
How did you solve it?

**Comment by NickCtrl** [comment]
Exactly the same issue! How did you solve it?
