### ISSUE TITLE
How to implement tracking algorithm on this code?

### ISSUE THREAD

**Issue by gorkem7** [qfgaohao/pytorch-ssd#98]
Hello, 
Thanks for this amazing repository, I would like to count cars on the street. Any idea how to implement tracking algorithm that tracks the cars and distinguish them? 
Thanks in advance.

**Comment by blacksailer** [comment]
You can use [this ](https://github.com/abewley/sort.git) project for tracking for example. Just pass detections from SSD to sort algorithm.
